import path from "node:path";

export function detectLanguage(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  const map: Record<string, string> = {
    ".ts": "typescript",
    ".tsx": "typescript-react",
    ".js": "javascript",
    ".jsx": "javascript-react",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".json": "json",
    ".py": "python",
    ".css": "css",
    ".html": "html",
    ".md": "markdown",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".cc": "cpp",
    ".c++": "cpp",
    ".h": "c-header",
    ".hpp": "cpp-header",
    ".hxx": "cpp-header",
    ".hh": "cpp-header",
    ".c": "c",
    ".cs": "csharp",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".scala": "scala",
    ".swift": "swift",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    ".r": "r",
    ".m": "objective-c",
    ".mm": "objective-cpp",
    ".dart": "dart",
    ".lua": "lua",
    ".pl": "perl",
    ".pm": "perl",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".sql": "sql",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".proto": "protobuf",
    ".vue": "vue",
    ".svelte": "svelte",
    ".astro": "astro",
    ".tex": "latex",
    ".ml": "ocaml",
    ".fs": "fsharp",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hrl": "erlang",
    ".hs": "haskell",
    ".lhs": "haskell",
    ".nim": "nim",
    ".zig": "zig",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".edn": "clojure",
    ".tf": "terraform",
    ".tfvars": "terraform",
    ".dockerfile": "dockerfile",
    ".sass": "sass",
    ".scss": "scss",
    ".less": "less"
  };
  return map[ext] ?? "text";
}
